version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mktest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tc2zlgz7iuy4"
s3_prefix = "mktest"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
